COPY INTO 's3://pfcbucket1/archive/ner_firehose_nlp_labeled/'
FROM (select CONTENT_ID
            ,POST_CREATED_USA_TIMESTAMP
            ,POST_ENTITY_NUMBER
            ,NER_DETECTED_GROUP
            ,NER_DETECTED_ENTITY
            ,NER_CONFIDENCE_SCORE
            ,RECORD_INSERTED_AT_TIMESTAMP
            ,RECORD_INSERTED_BY_USER
            ,RECORD_INSERTED_WITH_ROLE
FROM FIREHOSE_NLP_LABELED
)
STORAGE_INTEGRATION = STINT_S3_PFCBUCKET1
FILE_FORMAT = (
    TYPE = CSV
    COMPRESSION = AUTO
    RECORD_DELIMITER = '\n'
    FIELD_DELIMITER = ','
    FILE_EXTENSION = '.csv'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    EMPTY_FIELD_AS_NULL = FALSE
)
HEADER=TRUE;