USE ROLE USERADMIN;

---
--- NAMED_DATABASE Environment
---
-- ANALYST, SVCTRANSFORM personas omitted in this env

-- CREATE ROLE IF NOT EXISTS SHERLOCKWINGS_ANALYST_FR;
-- GRANT ROLE SHERLOCKWINGS_ANALYST_FR TO ROLE SHERLOCKWINGS_SYSADMIN;

CREATE ROLE IF NOT EXISTS SHERLOCKWINGS_ENGINEER_FR;
GRANT ROLE SHERLOCKWINGS_ENGINEER_FR TO ROLE SHERLOCKWINGS_SYSADMIN;

-- CREATE ROLE IF NOT EXISTS SHERLOCKWINGS_SVCTRANSFORM_FR;
-- GRANT ROLE SHERLOCKWINGS_SVCTRANSFORM_FR TO ROLE SHERLOCKWINGS_SYSADMIN;

CREATE ROLE IF NOT EXISTS SHERLOCKWINGS_ADMIN_FR;
GRANT ROLE SHERLOCKWINGS_ADMIN_FR TO ROLE SHERLOCKWINGS_SYSADMIN;


---
--- SANDBOX Environment
---
-- ANALYST, SVCTRANSFORM, ADMIN personas omitted in this env

-- CREATE ROLE IF NOT EXISTS SANDBOX_ANALYST_FR;
-- GRANT ROLE SANDBOX_ANALYST_FR TO ROLE SANDBOX_SYSADMIN;

CREATE ROLE IF NOT EXISTS SANDBOX_ENGINEER_FR;
GRANT ROLE SANDBOX_ENGINEER_FR TO ROLE SANDBOX_SYSADMIN;

-- CREATE ROLE IF NOT EXISTS SANDBOX_SVCTRANSFORM_FR;
-- GRANT ROLE SANDBOX_SVCTRANSFORM_FR TO ROLE SANDBOX_SYSADMIN;

CREATE ROLE IF NOT EXISTS SANDBOX_ADMIN_FR;
GRANT ROLE SANDBOX_ADMIN_FR TO ROLE SANDBOX_SYSADMIN;


---
--- DEV Environment
---

CREATE ROLE IF NOT EXISTS DEV_ANALYST_FR;
GRANT ROLE DEV_ANALYST_FR TO ROLE DEV_SYSADMIN;

CREATE ROLE IF NOT EXISTS DEV_ENGINEER_FR;
GRANT ROLE DEV_ENGINEER_FR TO ROLE DEV_SYSADMIN;

CREATE ROLE IF NOT EXISTS DEV_SVCTRANSFORM_FR;
GRANT ROLE DEV_SVCTRANSFORM_FR TO ROLE DEV_SYSADMIN;

CREATE ROLE IF NOT EXISTS DEV_ADMIN_FR;
GRANT ROLE DEV_ADMIN_FR TO ROLE DEV_SYSADMIN;


---
--- QA Environment
---

CREATE ROLE IF NOT EXISTS QA_ANALYST_FR;
GRANT ROLE QA_ANALYST_FR TO ROLE QA_SYSADMIN;

CREATE ROLE IF NOT EXISTS QA_ENGINEER_FR;
GRANT ROLE QA_ENGINEER_FR TO ROLE QA_SYSADMIN;

CREATE ROLE IF NOT EXISTS QA_SVCTRANSFORM_FR;
GRANT ROLE QA_SVCTRANSFORM_FR TO ROLE QA_SYSADMIN;

CREATE ROLE IF NOT EXISTS QA_ADMIN_FR;
GRANT ROLE QA_ADMIN_FR TO ROLE QA_SYSADMIN;


---
--- PROD Environment
--- ENGINER, ADMIN personas omitted in this environment

CREATE ROLE IF NOT EXISTS PROD_ANALYST_FR;
GRANT ROLE PROD_ANALYST_FR TO ROLE PROD_SYSADMIN;

-- CREATE ROLE IF NOT EXISTS PROD_ENGINEER_FR;
-- GRANT ROLE PROD_ENGINEER_FR TO ROLE PROD_SYSADMIN;

CREATE ROLE IF NOT EXISTS PROD_SVCTRANSFORM_FR;
GRANT ROLE PROD_SVCTRANSFORM_FR TO ROLE PROD_SYSADMIN;

-- CREATE ROLE IF NOT EXISTS PROD_ADMIN_FR;
-- GRANT ROLE PROD_ADMIN_FR TO ROLE PROD_SYSADMIN;
