--
-- NAMED_DATABASE Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "SHERLOCK_WINGS_ANALYST";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_ADMIN_FR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_ENGINEER_FR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_SVCTRANSFORM_FR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_ADMIN_FR";

--
-- SANDBOX Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "SANDBOX_ANALYST";
DROP ROLE IF EXISTS "SANDBOX_ADMIN_FR";
DROP ROLE IF EXISTS "SANDBOX_ENGINEER_FR";
DROP ROLE IF EXISTS "SANDBOX_SVCTRANSFORM_FR";
DROP ROLE IF EXISTS "SANDBOX_ADMIN_FR";

--
-- DEV Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "DEV_ANALYST";
DROP ROLE IF EXISTS "DEV_ADMIN_FR";
DROP ROLE IF EXISTS "DEV_ENGINEER_FR";
DROP ROLE IF EXISTS "DEV_SVCTRANSFORM_FR";
DROP ROLE IF EXISTS "DEV_ADMIN_FR";

--
-- QA Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "QA_ANALYST";
DROP ROLE IF EXISTS "QA_ADMIN_FR";
DROP ROLE IF EXISTS "QA_ENGINEER_FR";
DROP ROLE IF EXISTS "QA_SVCTRANSFORM_FR";
DROP ROLE IF EXISTS "QA_ADMIN_FR";

--
-- PROD Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "PROD_ANALYST";
DROP ROLE IF EXISTS "PROD_ADMIN_FR";
DROP ROLE IF EXISTS "PROD_ENGINEER_FR";
DROP ROLE IF EXISTS "PROD_SVCTRANSFORM_FR";
DROP ROLE IF EXISTS "PROD_ADMIN_FR";

