--
-- NAMED_DATABASE Environment
-- 

  -- Schema-level access roles
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "SHERLOCK_WINGS_EDW_UTIL_DB_R_AR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_EDW_UTIL_DB_RW_AR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_EDW_UTIL_DB_FULL_AR";

  -- Schema & DB Ownership
GRANT OWNERSHIP ON SCHEMA "SHERLOCK_WINGS_EDW_DB"."UTIL" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "SHERLOCK_WINGS_EDW_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;

  -- Warheouse access and ownership
DROP ROLE "SHERLOCK_WINGS_COMPUTE_U_AR";
DROP ROLE "SHERLOCK_WINGS_COMPUTE_UM_AR";
DROP ROLE "SHERLOCK_WINGS_COMPUTE_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "SANDBOX_COMPUTE_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- 
-- SANDBOX Environment
--

  -- Schema-level access roles
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "SHERLOCK_WINGS_EDW_UTIL_DB_R_AR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_EDW_UTIL_DB_RW_AR";
DROP ROLE IF EXISTS "SHERLOCK_WINGS_EDW_UTIL_DB_FULL_AR";

  -- Schema & DB Ownership
GRANT OWNERSHIP ON SCHEMA "SHERLOCK_WINGS_EDW_DB"."UTIL" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "SHERLOCK_WINGS_EDW_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;

  -- Warheouse access and ownership
DROP ROLE "SHERLOCK_WINGS_COMPUTE_U_AR";
DROP ROLE "SHERLOCK_WINGS_COMPUTE_UM_AR";
DROP ROLE "SHERLOCK_WINGS_COMPUTE_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "SANDBOX_COMPUTE_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;






--
-- DEV Environment
--

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "DEV_EDW_DB_MODEL_R_AR";
DROP ROLE IF EXISTS "DEV_EDW_DB_MODEL_RW_AR";
DROP ROLE IF EXISTS "DEV_EDW_DB_MODEL_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "DEV_EDW_DB"."MODEL" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "DEV_EDW_DB_RAW_R_AR";
DROP ROLE IF EXISTS "DEV_EDW_DB_RAW_RW_AR";
DROP ROLE IF EXISTS "DEV_EDW_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "DEV_EDW_DB"."RAW" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "DEV_EDW_DB_STAGE_R_AR";
DROP ROLE IF EXISTS "DEV_EDW_DB_STAGE_RW_AR";
DROP ROLE IF EXISTS "DEV_EDW_DB_STAGE_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "DEV_EDW_DB"."STAGE" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "DEV_EDW_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "DEV_COMPUTE_WH_U_AR";
DROP ROLE "DEV_COMPUTE_WH_UM_AR";
DROP ROLE "DEV_COMPUTE_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "DEV_COMPUTE_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;

--
-- PROD Environment
--

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "PROD_EDW_DB_MODEL_R_AR";
DROP ROLE IF EXISTS "PROD_EDW_DB_MODEL_RW_AR";
DROP ROLE IF EXISTS "PROD_EDW_DB_MODEL_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "PROD_EDW_DB"."MODEL" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "PROD_EDW_DB_RAW_R_AR";
DROP ROLE IF EXISTS "PROD_EDW_DB_RAW_RW_AR";
DROP ROLE IF EXISTS "PROD_EDW_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "PROD_EDW_DB"."RAW" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "PROD_EDW_DB_STAGE_R_AR";
DROP ROLE IF EXISTS "PROD_EDW_DB_STAGE_RW_AR";
DROP ROLE IF EXISTS "PROD_EDW_DB_STAGE_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "PROD_EDW_DB"."STAGE" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "PROD_EDW_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "PROD_COMPUTE_WH_U_AR";
DROP ROLE "PROD_COMPUTE_WH_UM_AR";
DROP ROLE "PROD_COMPUTE_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "PROD_COMPUTE_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;

--
-- QA Environment
--

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS "QA_EDW_DB_MODEL_R_AR";
DROP ROLE IF EXISTS "QA_EDW_DB_MODEL_RW_AR";
DROP ROLE IF EXISTS "QA_EDW_DB_MODEL_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "QA_EDW_DB"."MODEL" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "QA_EDW_DB_RAW_R_AR";
DROP ROLE IF EXISTS "QA_EDW_DB_RAW_RW_AR";
DROP ROLE IF EXISTS "QA_EDW_DB_RAW_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "QA_EDW_DB"."RAW" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE IF EXISTS "QA_EDW_DB_STAGE_R_AR";
DROP ROLE IF EXISTS "QA_EDW_DB_STAGE_RW_AR";
DROP ROLE IF EXISTS "QA_EDW_DB_STAGE_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "QA_EDW_DB"."STAGE" TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE "QA_EDW_DB" TO ROLE SYSADMIN COPY CURRENT GRANTS;
DROP ROLE "QA_COMPUTE_WH_U_AR";
DROP ROLE "QA_COMPUTE_WH_UM_AR";
DROP ROLE "QA_COMPUTE_WH_FULL_AR";
GRANT OWNERSHIP ON WAREHOUSE "QA_COMPUTE_WH" TO ROLE SYSADMIN COPY CURRENT GRANTS;

