/*
  Main analysis view: Trending words and phrases with sentiment breakdown
  
  This view combines trend data with sentiment information from post-level
  aggregated n-grams. Provides a complete picture of newly trending n-grams.
  
  Usage:
  Filter by TREND_CATEGORY in ('NEW', 'RAPID_GROWTH', 'STRONG_GROWTH') to see
  the most interesting trends. Adjust MIN_CURRENT_COUNT to filter by volume.
*/

CREATE OR REPLACE VIEW BLUESKY_DB.PFC.VW_TRENDING_WORDS_WITH_SENTIMENT AS
WITH trend_data AS (
  SELECT 
    CURRENT_MONTH,
    NGRAM,
    NGRAM_SIZE,
    CURRENT_COUNT,
    ABSOLUTE_CHANGE,
    GROWTH_RATE_PERCENT,
    IS_NEW_EMERGENCE,
    TREND_CATEGORY
  FROM BLUESKY_DB.PFC.VW_NGRAM_TRENDS
  WHERE TREND_CATEGORY IN ('NEW', 'RAPID_GROWTH', 'STRONG_GROWTH', 'MODERATE_GROWTH')
    AND CURRENT_COUNT >= 5  -- Minimum threshold: must appear at least 5 times
),
sentiment_pivot AS (
  SELECT 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN SENTIMENT_PERCENTAGE ELSE 0 END) AS PCT_POSITIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN SENTIMENT_PERCENTAGE ELSE 0 END) AS PCT_NEGATIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN SENTIMENT_PERCENTAGE ELSE 0 END) AS PCT_NEUTRAL,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN AVG_CONFIDENCE * OCCURRENCE_COUNT ELSE 0 END) / 
      NULLIF(SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN OCCURRENCE_COUNT ELSE 0 END), 0) AS AVG_CONF_POSITIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN AVG_CONFIDENCE * OCCURRENCE_COUNT ELSE 0 END) / 
      NULLIF(SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN OCCURRENCE_COUNT ELSE 0 END), 0) AS AVG_CONF_NEGATIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN AVG_CONFIDENCE * OCCURRENCE_COUNT ELSE 0 END) / 
      NULLIF(SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN OCCURRENCE_COUNT ELSE 0 END), 0) AS AVG_CONF_NEUTRAL,
    AVG(AVG_CONFIDENCE) AS AVG_CONFIDENCE_OVERALL
  FROM BLUESKY_DB.PFC.VW_MONTHLY_NGRAM_SENTIMENT
  GROUP BY 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE
)
SELECT 
  t.CURRENT_MONTH,
  t.NGRAM,
  t.NGRAM_SIZE,
  t.CURRENT_COUNT,
  t.ABSOLUTE_CHANGE,
  t.GROWTH_RATE_PERCENT,
  t.IS_NEW_EMERGENCE,
  t.TREND_CATEGORY,
  ROUND(COALESCE(s.PCT_POSITIVE, 0), 2) AS PCT_POSITIVE,
  ROUND(COALESCE(s.PCT_NEGATIVE, 0), 2) AS PCT_NEGATIVE,
  ROUND(COALESCE(s.PCT_NEUTRAL, 0), 2) AS PCT_NEUTRAL,
  ROUND(COALESCE(s.AVG_CONF_POSITIVE, 0), 4) AS AVG_CONF_POSITIVE,
  ROUND(COALESCE(s.AVG_CONF_NEGATIVE, 0), 4) AS AVG_CONF_NEGATIVE,
  ROUND(COALESCE(s.AVG_CONF_NEUTRAL, 0), 4) AS AVG_CONF_NEUTRAL,
  ROUND(COALESCE(s.AVG_CONFIDENCE_OVERALL, 0), 4) AS AVG_CONFIDENCE_OVERALL,
  CASE 
    WHEN COALESCE(s.PCT_POSITIVE, 0) >= GREATEST(
      COALESCE(s.PCT_NEGATIVE, 0), 
      COALESCE(s.PCT_NEUTRAL, 0)
    ) THEN 'Positive'
    WHEN COALESCE(s.PCT_NEGATIVE, 0) >= COALESCE(s.PCT_NEUTRAL, 0) THEN 'Negative'
    ELSE 'Neutral'
  END AS DOMINANT_SENTIMENT
FROM trend_data t
LEFT JOIN sentiment_pivot s
  ON t.CURRENT_MONTH = s.POST_MONTH
  AND t.NGRAM = s.NGRAM
  AND t.NGRAM_SIZE = s.NGRAM_SIZE
ORDER BY 
  t.CURRENT_MONTH DESC,
  CASE t.TREND_CATEGORY
    WHEN 'NEW' THEN 1
    WHEN 'RAPID_GROWTH' THEN 2
    WHEN 'STRONG_GROWTH' THEN 3
    WHEN 'MODERATE_GROWTH' THEN 4
    ELSE 5
  END,
  t.ABSOLUTE_CHANGE DESC;

