--
-- DEV Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "DEV_ADMIN_FR";
DROP ROLE IF EXISTS "DEV_ANALYST_FR";
DROP ROLE IF EXISTS "DEV_ENGINEER_FR";

--
-- PROD Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "PROD_ADMIN_FR";
DROP ROLE IF EXISTS "PROD_ANALYST_FR";
DROP ROLE IF EXISTS "PROD_ENGINEER_FR";

--
-- QA Environment
--

USE ROLE USERADMIN;
DROP ROLE IF EXISTS "QA_ADMIN_FR";
DROP ROLE IF EXISTS "QA_ANALYST_FR";
DROP ROLE IF EXISTS "QA_ENGINEER_FR";