--
-- DEV Environment
--

USE ROLE "DEV_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "DEV_EDW_DB";
CREATE SCHEMA IF NOT EXISTS "DEV_EDW_DB"."MODEL" WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS "DEV_EDW_DB"."RAW" WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS "DEV_EDW_DB"."STAGE" WITH MANAGED ACCESS;

--
-- PROD Environment
--

USE ROLE "PROD_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "PROD_EDW_DB";
CREATE SCHEMA IF NOT EXISTS "PROD_EDW_DB"."MODEL" WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS "PROD_EDW_DB"."RAW" WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS "PROD_EDW_DB"."STAGE" WITH MANAGED ACCESS;

--
-- QA Environment
--

USE ROLE "QA_SYSADMIN";
CREATE DATABASE IF NOT EXISTS "QA_EDW_DB";
CREATE SCHEMA IF NOT EXISTS "QA_EDW_DB"."MODEL" WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS "QA_EDW_DB"."RAW" WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS "QA_EDW_DB"."STAGE" WITH MANAGED ACCESS;