--
-- DEV Environment
--

USE ROLE "DEV_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "DEV_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "DEV_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;


--
-- PROD Environment
--

USE ROLE "PROD_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "PROD_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "PROD_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;


--
-- QA Environment
--

USE ROLE "QA_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "QA_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = MEDIUM;
ALTER WAREHOUSE "QA_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;
