--
-- SHERLOCK_WINGS Database (Utlities DB)
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS SHERLOCKWINGS_SYSADMIN;
GRANT ROLE SHERLOCKWINGS_SYSADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SHERLOCKWINGS_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SHERLOCKWINGS_SYSADMIN;

--
-- SANDBOX Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS SANDBOX_SYSADMIN;
GRANT ROLE SANDBOX_SYSADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SANDBOX_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SANDBOX_SYSADMIN;

--
-- DEV Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS DEV_SYSADMIN;
GRANT ROLE DEV_SYSADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE DEV_SYSADMIN;

--
-- QA Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS QA_SYSADMIN;
GRANT ROLE QA_SYSADMIN TO ROLE SYSADMIN;
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE QA_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE QA_SYSADMIN;

--
-- PROD Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS PROD_SYSADMIN;
GRANT ROLE PROD_SYSADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE PROD_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE PROD_SYSADMIN;
