/*

Need a DB that holds quality-of-life stuff, like the Clone-To-Sandbox Sproc, or a log table that 
records every SQL statement executed by user-created Stored Procedures.

This DB should usually take the name of the company or dev team on a real project. For this project,
I'm just calling the DB `SHERLOCKWINGS` since that's my github username. 

The high-level RBAC here will follow the same conventions as for all the other DBs/Environments
*/

--
-- NAMED_DATABASE Environment
--

USE ROLE SHERLOCKWINGS_SYSADMIN;
CREATE DATABASE IF NOT EXISTS SHERLOCKWINGS_EDW_DB;
CREATE SCHEMA IF NOT EXISTS SHERLOCKWINGS_EDW_DB.UTIL;

--
-- SANDBOX Environment
--

/*

We want to build the sandbox in such a way that it is schema-agnostic.
All schemas that are in the Sandbox are meant to only be clones of whatever is in the higher environment
the Sandbox data is cloned from. Those schemas get generated by the Clone-to-Sandbox Sproc, and all
relevant RBAC is applied by the sproc on-the-fly. 

The only built-in RBAC for Sandbox will be at the DB level. 

*/
USE ROLE SANDBOX_SYSADMIN;
CREATE DATABASE IF NOT EXISTS SANDBOX_EDW_DB;
CREATE SCHEMA IF NOT EXISTS SANDBOX_EDW_DB.UTIL;

--
-- DEV Environment
--

USE ROLE DEV_SYSADMIN;
CREATE DATABASE IF NOT EXISTS DEV_EDW_DB;
CREATE SCHEMA IF NOT EXISTS DEV_EDW_DB.MODEL WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS DEV_EDW_DB.RAW WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS DEV_EDW_DB.STAGE WITH MANAGED ACCESS;

--
-- QA Environment
--

USE ROLE QA_SYSADMIN;
CREATE DATABASE IF NOT EXISTS QA_EDW_DB;
CREATE SCHEMA IF NOT EXISTS QA_EDW_DB.MODEL WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS QA_EDW_DB.RAW WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS QA_EDW_DB.STAGE WITH MANAGED ACCESS;

--
-- PROD Environment
--

USE ROLE PROD_SYSADMIN;
CREATE DATABASE IF NOT EXISTS PROD_EDW_DB;
CREATE SCHEMA IF NOT EXISTS PROD_EDW_DB.MODEL WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS PROD_EDW_DB.RAW WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS PROD_EDW_DB.STAGE WITH MANAGED ACCESS;
