--
-- NAMED_DATABASE Environment
--

USE ROLE "SHERLOCKWINGS_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "SHERLOCKWINGS_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "SHERLOCKWINGS_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;


--
-- SANDBOX Environment
--

USE ROLE "SANDBOX_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "SANDBOX_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "SANDBOX_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

--
-- DEV Environment
--

USE ROLE "DEV_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "DEV_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "DEV_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;

--
-- QA Environment
--

USE ROLE "QA_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "QA_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "QA_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;


--
-- PROD Environment
--

USE ROLE "PROD_SYSADMIN";

CREATE WAREHOUSE IF NOT EXISTS "PROD_COMPUTE_WH" WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE "PROD_COMPUTE_WH" SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;
