--
-- SHERLOCK_WINGS Database (Utlities DB)
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS ADMIN_FR;
GRANT ROLE SHERLOCKWINGS_SYSADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ADMIN_FR;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ADMIN_FR;


--
-- SANDBOX Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS SANDBOX_SYSADMIN;
GRANT ROLE SANDBOX_SYSADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SANDBOX_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SANDBOX_SYSADMIN;
