-- Single warehouse, xsmall. KISS principle

USE ROLE ADMIN_FR;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH INITIALLY_SUSPENDED = TRUE WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE COMPUTE_WH SET
WAIT_FOR_COMPLETION = TRUE
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
ENABLE_QUERY_ACCELERATION = FALSE
WAREHOUSE_TYPE = STANDARD;