USE ROLE USERADMIN;

-- Only FRs we need besides admin are a DEV fr and a Read-only fr

CREATE ROLE IF NOT EXISTS DEV_FR;
GRANT ROLE DEV_FR TO ROLE ADMIN_FR;

CREATE ROLE IF NOT EXISTS READ_FR;
GRANT ROLE READ_FR TO ROLE ADMIN_FR;