USE ROLE USERADMIN;
-- MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | 
-- MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | 
-- MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | MAIN SCHEMA | 

    -- READ ONLY ARs

CREATE ROLE IF NOT EXISTS BLUESKY_DB_MAIN_R_AR;
GRANT ROLE BLUESKY_DB_MAIN_R_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- DB access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_MAIN_R_AR;

-- Schema access
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- Table access
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- View access
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- Sequence access
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- Stage access
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- File format access
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- Stream access
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- Sproc access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;

-- UDF access
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_R_AR;




USE ROLE USERADMIN;
-- MAIN SCHEMA
    -- READ/WRITE ARs


CREATE ROLE IF NOT EXISTS BLUESKY_DB_MAIN_RW_AR;
GRANT ROLE BLUESKY_DB_MAIN_RW_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- Schema access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT CREATE VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- No privs to run this on my bozo free account!  ( ﾟ，_ゝ｀)
-- GRANT CREATE MATERIALIZED VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

GRANT CREATE SEQUENCE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT CREATE STAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT CREATE FILE FORMAT ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT CREATE FUNCTION ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;


-- Table access
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT INSERT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT UPDATE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT DELETE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT REFERENCES ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- View access
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- Sequence access
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- Stage access
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT WRITE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT WRITE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;


-- File format access
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- Stream access
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- Sproc access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- UDF access
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- Materialized view access
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;

-- Task Access
GRANT MONITOR ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT OPERATE ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_RW_AR;





USE ROLE USERADMIN;
-- MAIN SCHEMA
    -- FULL ARs

-- Instantiate role and the environment SYSADMIN's inheritance of it
CREATE ROLE IF NOT EXISTS BLUESKY_DB_MAIN_FULL_AR;
GRANT ROLE BLUESKY_DB_MAIN_FULL_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- Schema access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE SEQUENCE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE STAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE FILE FORMAT ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE STREAM ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE PROCEDURE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE FUNCTION ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE TASK ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;


-- Table access
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT INSERT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT UPDATE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT DELETE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT REFERENCES ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- View access
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- Sequence access
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- Stage access
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT WRITE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT WRITE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;


-- File format access
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- Stream access
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- Sproc access
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- UDF access
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- Materialized view access
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;

-- Task Access
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT MONITOR ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OPERATE ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_MAIN_FULL_AR;


-- STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | 
-- STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | 
-- STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | STEETS SCHEMA | 

    -- READ ONLY ARs

CREATE ROLE IF NOT EXISTS BLUESKY_DB_STEETS_R_AR;
GRANT ROLE BLUESKY_DB_STEETS_R_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- DB access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_STEETS_R_AR;

-- Schema access
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- Table access
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- View access
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- Sequence access
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- Stage access
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- File format access
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- Stream access
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- Sproc access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;

-- UDF access
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_R_AR;




USE ROLE USERADMIN;
-- MAIN SCHEMA
    -- READ/WRITE ARs


CREATE ROLE IF NOT EXISTS BLUESKY_DB_STEETS_RW_AR;
GRANT ROLE BLUESKY_DB_STEETS_RW_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- Schema access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT CREATE VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- No privs to run this on my bozo free account!  ( ﾟ，_ゝ｀)
-- GRANT CREATE MATERIALIZED VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

GRANT CREATE SEQUENCE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT CREATE STAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT CREATE FILE FORMAT ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT CREATE FUNCTION ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;


-- Table access
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT INSERT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT UPDATE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT DELETE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT REFERENCES ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- View access
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- Sequence access
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- Stage access
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT WRITE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT WRITE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;


-- File format access
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- Stream access
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- Sproc access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- UDF access
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- Materialized view access
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;

-- Task Access
GRANT MONITOR ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT OPERATE ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_RW_AR;





USE ROLE USERADMIN;
-- MAIN SCHEMA
    -- FULL ARs

-- Instantiate role and the environment SYSADMIN's inheritance of it
CREATE ROLE IF NOT EXISTS BLUESKY_DB_STEETS_FULL_AR;
GRANT ROLE BLUESKY_DB_STEETS_FULL_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- Schema access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE SEQUENCE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE STAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE FILE FORMAT ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE STREAM ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE PROCEDURE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE FUNCTION ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE TASK ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;


-- Table access
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT INSERT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT UPDATE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT DELETE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT REFERENCES ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- View access
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- Sequence access
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- Stage access
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT WRITE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT WRITE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;


-- File format access
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- Stream access
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- Sproc access
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- UDF access
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- Materialized view access
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;

-- Task Access
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT MONITOR ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OPERATE ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_STEETS_FULL_AR;



-- PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | 
-- PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | 
-- PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | PFC SCHEMA | 

    -- READ ONLY ARs

CREATE ROLE IF NOT EXISTS BLUESKY_DB_PFC_R_AR;
GRANT ROLE BLUESKY_DB_PFC_R_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- DB access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_PFC_R_AR;

-- Schema access
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- Table access
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- View access
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- Sequence access
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- Stage access
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- File format access
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- Stream access
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- Sproc access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;

-- UDF access
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_R_AR;




USE ROLE USERADMIN;
-- MAIN SCHEMA
    -- READ/WRITE ARs


CREATE ROLE IF NOT EXISTS BLUESKY_DB_PFC_RW_AR;
GRANT ROLE BLUESKY_DB_PFC_RW_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- Schema access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT CREATE VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- No privs to run this on my bozo free account!  ( ﾟ，_ゝ｀)
-- GRANT CREATE MATERIALIZED VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

GRANT CREATE SEQUENCE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT CREATE STAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT CREATE FILE FORMAT ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT CREATE FUNCTION ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;


-- Table access
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT INSERT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT UPDATE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT DELETE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT REFERENCES ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- View access
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- Sequence access
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- Stage access
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT WRITE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT WRITE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;


-- File format access
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- Stream access
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- Sproc access
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- UDF access
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- Materialized view access
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;

-- Task Access
GRANT MONITOR ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT OPERATE ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_RW_AR;





USE ROLE USERADMIN;
-- MAIN SCHEMA
    -- FULL ARs

-- Instantiate role and the environment SYSADMIN's inheritance of it
CREATE ROLE IF NOT EXISTS BLUESKY_DB_PFC_FULL_AR;
GRANT ROLE BLUESKY_DB_PFC_FULL_AR TO ROLE ADMIN_FR;

USE ROLE SECURITYADMIN;

-- Schema access
GRANT USAGE ON DATABASE BLUESKY_DB TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE VIEW ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE SEQUENCE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE STAGE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE FILE FORMAT ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE STREAM ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE PROCEDURE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE FUNCTION ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE TASK ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;


-- Table access
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT CREATE TABLE ON SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT INSERT ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT UPDATE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT DELETE ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT REFERENCES ON ALL TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- View access
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON ALL VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- Sequence access
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- Stage access
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT READ ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT READ ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT WRITE ON FUTURE STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT WRITE ON ALL STAGES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;


-- File format access
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- Stream access
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON ALL STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- Sproc access
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- UDF access
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- Materialized view access
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;

-- Task Access
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT MONITOR ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OPERATE ON ALL TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA BLUESKY_DB.MAIN TO ROLE BLUESKY_DB_PFC_FULL_AR;





-- WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | 
-- WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | 
-- WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | WAREHOUSES | 

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS COMPUTE_WH_O_AR;
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON WAREHOUSE COMPUTE_WH TO ROLE COMPUTE_WH_O_AR;
GRANT ROLE COMPUTE_WH_O_AR TO ROLE ADMIN_FR;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS COMPUTE_WH_UW_AR;
GRANT ROLE COMPUTE_WH_UW_AR TO ROLE ADMIN_FR;
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPUTE_WH_UW_AR;
GRANT MONITOR ON WAREHOUSE COMPUTE_WH TO ROLE COMPUTE_WH_UW_AR;


USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS COMPUTE_WH_U_AR;
GRANT ROLE COMPUTE_WH_U_AR TO ROLE ADMIN_FR;
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPUTE_WH_U_AR;




/*
FUNCTIONAL ROLE APPLICATION

DEV_FR gets full access on PFC and STEETS, read-only on MAIN
ADMIN_FR gets full access to all schemas and DBs
READ_FR gets read-only access to all schemas and DBs

DEV_FR gets Use-Watch access to COMPUTE_WH
ADMIN_FR gets Owner access to COMPUTE_WH
READ_FR gets Use access to COMPUTE_WH

*/
grant role BLUESKY_DB_MAIN_R_AR      to role DEV_FR;
grant role BLUESKY_DB_STEETS_FULL_AR to role DEV_FR;
grant role BLUESKY_DB_PFC_FULL_AR    to role DEV_FR;

grant role BLUESKY_DB_MAIN_FULL_AR   to role ADMIN_FR;
grant role BLUESKY_DB_STEETS_FULL_AR to role ADMIN_FR;
grant role BLUESKY_DB_PFC_FULL_AR    to role ADMIN_FR;

grant role BLUESKY_DB_MAIN_R_AR   to role READ_FR;
grant role BLUESKY_DB_STEETS_R_AR to role READ_FR;
grant role BLUESKY_DB_PFC_R_AR    to role READ_FR;

grant role COMPUTE_WH_UW_AR to role DEV_FR;
grant role COMPUTE_WH_O_AR  to role ADMIN_FR;
grant role COMPUTE_WH_U_AR  to role READ_FR;
