USE ROLE USERADMIN;

GRANT ROLE ADMIN_FR TO USER HOBBYMAN;
GRANT ROLE DEV_FR TO USER HOBBYMAN;
GRANT ROLE READ_FR TO USER HOBBYMAN;

-- CREATE USER IF NOT EXISTS SGCHASTAIN
--   PASSWORD = '$teetz_Log!n'
--   LOGIN_NAME = SGCHASTAIN
--   DISPLAY_NAME = SGCHASTAIN
--   FIRST_NAME = Stephen
--   MIDDLE_NAME = G
--   LAST_NAME = CHASTAIN
--   EMAIL = <string>
--   MUST_CHANGE_PASSWORD = TRUE 
--   DISABLED = TRUE | FALSE
--   DEFAULT_WAREHOUSE = COMPUTE_WH
--   DEFAULT_NAMESPACE = <string>
--   DEFAULT_ROLE = READ_FR
--   TYPE = PERSON;

-- GRANT ROLE READ_FR TO USER SGCHASTAIN;
-- GRANT ROLE DEV_FR TO USER SGCHASTAIN;