USE ROLE USERADMIN;

GRANT ROLE ADMIN_FR TO USER HOBBYMAN;
GRANT ROLE DEV_FR TO USER HOBBYMAN;
GRANT ROLE READ_FR TO USER HOBBYMAN;
grant role task_sproc_runner_ar to user hobbyman; 


-- make an account for my data buddy
CREATE USER IF NOT EXISTS SGCHASTAIN
  PASSWORD = '$teetz_Log!n' -- one-time PW that is changed
  LOGIN_NAME = SGCHASTAIN
  DISPLAY_NAME = SGCHASTAIN
  FIRST_NAME = Stephen
  MIDDLE_NAME = G
  LAST_NAME = CHASTAIN
  EMAIL = <string>
  MUST_CHANGE_PASSWORD = TRUE 
  DISABLED = TRUE | FALSE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = <string>
  DEFAULT_ROLE = READ_FR
  TYPE = PERSON;

GRANT ROLE READ_FR TO USER SGCHASTAIN;
GRANT ROLE DEV_FR TO USER SGCHASTAIN;

-- make a robot account for CLI stuff
CREATE USER IF NOT EXISTS SVC_SNOWCLI
  LOGIN_NAME = SVC_SNOWCLI
  DISPLAY_NAME = SVC_SNOWCLI
  DISABLED = FALSE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_ROLE = DEV_FR
  TYPE = SERVICE
  RSA_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwvvJmTiG40OYuRzU5VC2
26vZqYiTLm1S3zq6J2yRNfAheLMaVsrcEgXsrJ/NljlOkmCGjp5agZ5ghmHXqdNt
yRCau/c4KIDl7ZNsQ3RX6svVomwXA2whGkR/vDorRveUTc40xNahfHirqPCUb0AO
otJAhCnFSR7rswEwGchlX/G/VOmFAwz6ZtLl6xLbulmzNa5cEgYEFj0pWjcKtBzT
WJt0vXQIS86lVoJ4CaJED8oeteWSEATRFXmTslcHbpynVRV0rGZ/TdExYVRvM1py
eZMNaqRShKmkPGUWXoWmkS7k1TRnP3XvcMlOpr6JaOCR9gaJrzCIF8uqvZgwyx5C
/wIDAQAB
-----END PUBLIC KEY-----';


GRANT ROLE READ_FR TO USER SVC_SNOWCLI;
GRANT ROLE DEV_FR TO USER SVC_SNOWCLI;
