/*
  Run all views in order to set up the word trends analysis
  
  Execute this script to create all views needed for trending words analysis.
  Run in order as views depend on each other.
*/

-- Step 1: Extract n-grams from post text
CREATE OR REPLACE VIEW BLUESKY_DB.PFC.VW_POST_NGRAMS AS
WITH cleaned_text AS (
  SELECT 
    p.CONTENT_ID,
    DATE_TRUNC('MONTH', p.POST_CREATED_AT_TIMESTAMP) AS POST_MONTH,
    -- Normalize text: lowercase, remove URLs, handle hashtags/mentions
    REGEXP_REPLACE(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          LOWER(TRIM(p.POST_TEXT)),
          'https?://\\S+', '', 1, 0, 'i'  -- Remove URLs
        ),
        '@\\w+', '', 1, 0  -- Remove mentions (optional - might want to keep)
      ),
      '[^a-z0-9\\s]', ' ', 1, 0  -- Replace punctuation with spaces
    ) AS CLEANED_TEXT
  FROM BLUESKY_DB.MAIN.FIREHOSE_PROCESSED p
  WHERE p.POST_TEXT IS NOT NULL
    AND p.POST_TEXT != ''
    AND LENGTH(TRIM(p.POST_TEXT)) > 0
),
tokenized AS (
  SELECT 
    CONTENT_ID,
    POST_MONTH,
    CLEANED_TEXT,
    -- Split text into array of words
    SPLIT(REGEXP_REPLACE(TRIM(CLEANED_TEXT), '\\s+', ' ', 1, 0), ' ') AS WORDS_ARRAY
  FROM cleaned_text
  WHERE CLEANED_TEXT IS NOT NULL
    AND LENGTH(TRIM(CLEANED_TEXT)) > 0
),
words_flat AS (
  SELECT 
    t.CONTENT_ID,
    t.POST_MONTH,
    w.VALUE AS WORD,
    w.INDEX AS WORD_POSITION
  FROM tokenized t,
  LATERAL FLATTEN(INPUT => t.WORDS_ARRAY) w
  WHERE LENGTH(TRIM(w.VALUE)) >= 2  -- Minimum 2 characters per word
),
-- 1-grams (single words)
unigrams AS (
  SELECT 
    CONTENT_ID,
    POST_MONTH,
    WORD AS NGRAM,
    1 AS NGRAM_SIZE,
    WORD_POSITION AS START_POSITION
  FROM words_flat
),
-- 2-grams (word pairs)
bigrams AS (
  SELECT 
    w1.CONTENT_ID,
    w1.POST_MONTH,
    w1.WORD || ' ' || w2.WORD AS NGRAM,
    2 AS NGRAM_SIZE,
    w1.WORD_POSITION AS START_POSITION
  FROM words_flat w1
  INNER JOIN words_flat w2
    ON w1.CONTENT_ID = w2.CONTENT_ID
    AND w1.POST_MONTH = w2.POST_MONTH
    AND w2.WORD_POSITION = w1.WORD_POSITION + 1
),
-- 3-grams (three-word phrases)
trigrams AS (
  SELECT 
    w1.CONTENT_ID,
    w1.POST_MONTH,
    w1.WORD || ' ' || w2.WORD || ' ' || w3.WORD AS NGRAM,
    3 AS NGRAM_SIZE,
    w1.WORD_POSITION AS START_POSITION
  FROM words_flat w1
  INNER JOIN words_flat w2
    ON w1.CONTENT_ID = w2.CONTENT_ID
    AND w1.POST_MONTH = w2.POST_MONTH
    AND w2.WORD_POSITION = w1.WORD_POSITION + 1
  INNER JOIN words_flat w3
    ON w1.CONTENT_ID = w3.CONTENT_ID
    AND w1.POST_MONTH = w3.POST_MONTH
    AND w3.WORD_POSITION = w2.WORD_POSITION + 1
),
-- Combine all n-grams
all_ngrams AS (
  SELECT * FROM unigrams
  UNION ALL
  SELECT * FROM bigrams
  UNION ALL
  SELECT * FROM trigrams
)
SELECT DISTINCT
  CONTENT_ID,
  POST_MONTH,
  NGRAM,
  NGRAM_SIZE,
  START_POSITION
FROM all_ngrams
WHERE LENGTH(TRIM(NGRAM)) >= 2;  -- Final validation

-- Step 2: Calculate monthly counts with sentiment
CREATE OR REPLACE VIEW BLUESKY_DB.PFC.VW_MONTHLY_NGRAM_SENTIMENT AS
WITH ngram_sentiment_base AS (
  SELECT 
    n.CONTENT_ID,
    n.POST_MONTH,
    n.NGRAM,
    n.NGRAM_SIZE,
    COALESCE(s.SENTIMENT_DETECTED_LABEL, 'Unknown') AS SENTIMENT_LABEL,
    COALESCE(s.SENTIMENT_CONFIDENCE_SCORE, 0) AS SENTIMENT_CONFIDENCE
  FROM BLUESKY_DB.PFC.VW_POST_NGRAMS n
  LEFT JOIN BLUESKY_DB.MAIN.FIREHOSE_NLP_LABELED s
    ON n.CONTENT_ID = s.CONTENT_ID
),
monthly_aggregates AS (
  SELECT 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    SENTIMENT_LABEL,
    COUNT(*) AS OCCURRENCE_COUNT,
    COUNT(DISTINCT CONTENT_ID) AS POST_COUNT,
    AVG(SENTIMENT_CONFIDENCE) AS AVG_CONFIDENCE,
    MIN(SENTIMENT_CONFIDENCE) AS MIN_CONFIDENCE,
    MAX(SENTIMENT_CONFIDENCE) AS MAX_CONFIDENCE
  FROM ngram_sentiment_base
  GROUP BY 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    SENTIMENT_LABEL
),
sentiment_totals AS (
  SELECT 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    SUM(OCCURRENCE_COUNT) AS TOTAL_OCCURRENCES,
    SUM(POST_COUNT) AS TOTAL_POSTS
  FROM monthly_aggregates
  GROUP BY 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE
)
SELECT 
  m.POST_MONTH,
  m.NGRAM,
  m.NGRAM_SIZE,
  m.SENTIMENT_LABEL,
  m.OCCURRENCE_COUNT,
  m.POST_COUNT,
  m.AVG_CONFIDENCE,
  m.MIN_CONFIDENCE,
  m.MAX_CONFIDENCE,
  t.TOTAL_OCCURRENCES,
  t.TOTAL_POSTS,
  -- Calculate sentiment percentage
  ROUND(
    (m.OCCURRENCE_COUNT * 100.0 / NULLIF(t.TOTAL_OCCURRENCES, 0)),
    2
  ) AS SENTIMENT_PERCENTAGE
FROM monthly_aggregates m
INNER JOIN sentiment_totals t
  ON m.POST_MONTH = t.POST_MONTH
  AND m.NGRAM = t.NGRAM
  AND m.NGRAM_SIZE = t.NGRAM_SIZE
ORDER BY 
  m.POST_MONTH,
  t.TOTAL_OCCURRENCES DESC,
  m.SENTIMENT_LABEL;

-- Step 3: Calculate month-over-month trends
CREATE OR REPLACE VIEW BLUESKY_DB.PFC.VW_NGRAM_TRENDS AS
WITH monthly_totals AS (
  -- Get total occurrences per n-gram per month (regardless of sentiment)
  SELECT 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    TOTAL_OCCURRENCES,
    TOTAL_POSTS
  FROM BLUESKY_DB.PFC.VW_MONTHLY_NGRAM_SENTIMENT
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY POST_MONTH, NGRAM, NGRAM_SIZE 
    ORDER BY POST_MONTH, NGRAM, NGRAM_SIZE
  ) = 1  -- Get one row per month/ngram (we only need totals)
),
month_comparison AS (
  SELECT 
    curr.POST_MONTH AS CURRENT_MONTH,
    curr.NGRAM,
    curr.NGRAM_SIZE,
    curr.TOTAL_OCCURRENCES AS CURRENT_COUNT,
    curr.TOTAL_POSTS AS CURRENT_POSTS,
    -- Previous month data
    prev.POST_MONTH AS PREVIOUS_MONTH,
    COALESCE(prev.TOTAL_OCCURRENCES, 0) AS PREVIOUS_COUNT,
    COALESCE(prev.TOTAL_POSTS, 0) AS PREVIOUS_POSTS
  FROM monthly_totals curr
  LEFT JOIN monthly_totals prev
    ON curr.NGRAM = prev.NGRAM
    AND curr.NGRAM_SIZE = prev.NGRAM_SIZE
    AND prev.POST_MONTH = DATEADD(MONTH, -1, curr.POST_MONTH)
),
trend_metrics AS (
  SELECT 
    CURRENT_MONTH,
    NGRAM,
    NGRAM_SIZE,
    CURRENT_COUNT,
    CURRENT_POSTS,
    PREVIOUS_MONTH,
    PREVIOUS_COUNT,
    PREVIOUS_POSTS,
    -- Absolute change
    CURRENT_COUNT - PREVIOUS_COUNT AS ABSOLUTE_CHANGE,
    -- Growth rate (handle division by zero)
    CASE 
      WHEN PREVIOUS_COUNT = 0 AND CURRENT_COUNT > 0 THEN 999999  -- New emergence (use large number)
      WHEN PREVIOUS_COUNT > 0 THEN 
        ROUND((CURRENT_COUNT - PREVIOUS_COUNT) * 100.0 / PREVIOUS_COUNT, 2)
      ELSE 0
    END AS GROWTH_RATE_PERCENT,
    -- Growth multiplier (how many times more than previous)
    CASE 
      WHEN PREVIOUS_COUNT = 0 AND CURRENT_COUNT > 0 THEN NULL  -- Cannot calculate multiplier for new
      WHEN PREVIOUS_COUNT > 0 THEN 
        ROUND(CURRENT_COUNT * 1.0 / PREVIOUS_COUNT, 2)
      ELSE NULL
    END AS GROWTH_MULTIPLIER,
    -- Is this a new trend? (didn't exist in previous month)
    CASE WHEN PREVIOUS_COUNT = 0 AND CURRENT_COUNT > 0 THEN TRUE ELSE FALSE END AS IS_NEW_EMERGENCE
  FROM month_comparison
)
SELECT 
  CURRENT_MONTH,
  NGRAM,
  NGRAM_SIZE,
  CURRENT_COUNT,
  CURRENT_POSTS,
  PREVIOUS_MONTH,
  PREVIOUS_COUNT,
  PREVIOUS_POSTS,
  ABSOLUTE_CHANGE,
  GROWTH_RATE_PERCENT,
  GROWTH_MULTIPLIER,
  IS_NEW_EMERGENCE,
  -- Trend classification
  CASE 
    WHEN IS_NEW_EMERGENCE THEN 'NEW'
    WHEN GROWTH_RATE_PERCENT >= 100 THEN 'RAPID_GROWTH'
    WHEN GROWTH_RATE_PERCENT >= 50 THEN 'STRONG_GROWTH'
    WHEN GROWTH_RATE_PERCENT >= 20 THEN 'MODERATE_GROWTH'
    WHEN GROWTH_RATE_PERCENT > 0 THEN 'SLOW_GROWTH'
    WHEN GROWTH_RATE_PERCENT = 0 THEN 'STABLE'
    ELSE 'DECLINING'
  END AS TREND_CATEGORY
FROM trend_metrics
ORDER BY 
  CURRENT_MONTH DESC,
  ABSOLUTE_CHANGE DESC,
  GROWTH_RATE_PERCENT DESC;

-- Step 4: Final trending words view with sentiment
CREATE OR REPLACE VIEW BLUESKY_DB.PFC.VW_TRENDING_WORDS_WITH_SENTIMENT AS
WITH trend_data AS (
  SELECT 
    CURRENT_MONTH,
    NGRAM,
    NGRAM_SIZE,
    CURRENT_COUNT,
    ABSOLUTE_CHANGE,
    GROWTH_RATE_PERCENT,
    IS_NEW_EMERGENCE,
    TREND_CATEGORY
  FROM BLUESKY_DB.PFC.VW_NGRAM_TRENDS
  WHERE TREND_CATEGORY IN ('NEW', 'RAPID_GROWTH', 'STRONG_GROWTH', 'MODERATE_GROWTH')
    AND CURRENT_COUNT >= 5  -- Minimum threshold: must appear at least 5 times
),
sentiment_pivot AS (
  SELECT 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    -- Pivot sentiment labels into columns
    SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN SENTIMENT_PERCENTAGE ELSE 0 END) AS PCT_POSITIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN SENTIMENT_PERCENTAGE ELSE 0 END) AS PCT_NEGATIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN SENTIMENT_PERCENTAGE ELSE 0 END) AS PCT_NEUTRAL,
    -- Weighted average confidence (weighted by occurrence count)
    SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN AVG_CONFIDENCE * OCCURRENCE_COUNT ELSE 0 END) / 
      NULLIF(SUM(CASE WHEN SENTIMENT_LABEL = 'Positive' THEN OCCURRENCE_COUNT ELSE 0 END), 0) AS AVG_CONF_POSITIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN AVG_CONFIDENCE * OCCURRENCE_COUNT ELSE 0 END) / 
      NULLIF(SUM(CASE WHEN SENTIMENT_LABEL = 'Negative' THEN OCCURRENCE_COUNT ELSE 0 END), 0) AS AVG_CONF_NEGATIVE,
    SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN AVG_CONFIDENCE * OCCURRENCE_COUNT ELSE 0 END) / 
      NULLIF(SUM(CASE WHEN SENTIMENT_LABEL = 'Neutral' THEN OCCURRENCE_COUNT ELSE 0 END), 0) AS AVG_CONF_NEUTRAL,
    -- Overall average confidence
    AVG(AVG_CONFIDENCE) AS AVG_CONFIDENCE_OVERALL
  FROM BLUESKY_DB.PFC.VW_MONTHLY_NGRAM_SENTIMENT
  GROUP BY 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE
)
SELECT 
  t.CURRENT_MONTH,
  t.NGRAM,
  t.NGRAM_SIZE,
  t.CURRENT_COUNT,
  t.ABSOLUTE_CHANGE,
  t.GROWTH_RATE_PERCENT,
  t.IS_NEW_EMERGENCE,
  t.TREND_CATEGORY,
  -- Sentiment percentages
  ROUND(COALESCE(s.PCT_POSITIVE, 0), 2) AS PCT_POSITIVE,
  ROUND(COALESCE(s.PCT_NEGATIVE, 0), 2) AS PCT_NEGATIVE,
  ROUND(COALESCE(s.PCT_NEUTRAL, 0), 2) AS PCT_NEUTRAL,
  -- Average confidence scores
  ROUND(COALESCE(s.AVG_CONF_POSITIVE, 0), 4) AS AVG_CONF_POSITIVE,
  ROUND(COALESCE(s.AVG_CONF_NEGATIVE, 0), 4) AS AVG_CONF_NEGATIVE,
  ROUND(COALESCE(s.AVG_CONF_NEUTRAL, 0), 4) AS AVG_CONF_NEUTRAL,
  ROUND(COALESCE(s.AVG_CONFIDENCE_OVERALL, 0), 4) AS AVG_CONFIDENCE_OVERALL,
  -- Dominant sentiment (highest percentage)
  CASE 
    WHEN COALESCE(s.PCT_POSITIVE, 0) >= GREATEST(
      COALESCE(s.PCT_NEGATIVE, 0), 
      COALESCE(s.PCT_NEUTRAL, 0)
    ) THEN 'Positive'
    WHEN COALESCE(s.PCT_NEGATIVE, 0) >= COALESCE(s.PCT_NEUTRAL, 0) THEN 'Negative'
    ELSE 'Neutral'
  END AS DOMINANT_SENTIMENT
FROM trend_data t
LEFT JOIN sentiment_pivot s
  ON t.CURRENT_MONTH = s.POST_MONTH
  AND t.NGRAM = s.NGRAM
  AND t.NGRAM_SIZE = s.NGRAM_SIZE
ORDER BY 
  t.CURRENT_MONTH DESC,
  CASE t.TREND_CATEGORY
    WHEN 'NEW' THEN 1
    WHEN 'RAPID_GROWTH' THEN 2
    WHEN 'STRONG_GROWTH' THEN 3
    WHEN 'MODERATE_GROWTH' THEN 4
    ELSE 5
  END,
  t.ABSOLUTE_CHANGE DESC;

