/*
  Calculate month-over-month trends for n-grams
  
  This view compares n-gram usage between consecutive months to identify:
  - Newly emerging n-grams (zero to something)
  - Growing n-grams (significant month-over-month increase)
  - Growth rates and absolute increases
  
  Works with post-level aggregated data for efficiency.
*/

CREATE OR REPLACE VIEW BLUESKY_DB.PFC.VW_NGRAM_TRENDS AS
WITH monthly_totals AS (
  -- Get total occurrences per n-gram per month (regardless of sentiment)
  SELECT 
    POST_MONTH,
    NGRAM,
    NGRAM_SIZE,
    TOTAL_OCCURRENCES,
    TOTAL_POSTS
  FROM BLUESKY_DB.PFC.VW_MONTHLY_NGRAM_SENTIMENT
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY POST_MONTH, NGRAM, NGRAM_SIZE 
    ORDER BY POST_MONTH, NGRAM, NGRAM_SIZE
  ) = 1
),
month_comparison AS (
  SELECT 
    curr.POST_MONTH AS CURRENT_MONTH,
    curr.NGRAM,
    curr.NGRAM_SIZE,
    curr.TOTAL_OCCURRENCES AS CURRENT_COUNT,
    curr.TOTAL_POSTS AS CURRENT_POSTS,
    prev.POST_MONTH AS PREVIOUS_MONTH,
    COALESCE(prev.TOTAL_OCCURRENCES, 0) AS PREVIOUS_COUNT,
    COALESCE(prev.TOTAL_POSTS, 0) AS PREVIOUS_POSTS
  FROM monthly_totals curr
  LEFT JOIN monthly_totals prev
    ON curr.NGRAM = prev.NGRAM
    AND curr.NGRAM_SIZE = prev.NGRAM_SIZE
    AND prev.POST_MONTH = DATEADD(MONTH, -1, curr.POST_MONTH)
),
trend_metrics AS (
  SELECT 
    CURRENT_MONTH,
    NGRAM,
    NGRAM_SIZE,
    CURRENT_COUNT,
    CURRENT_POSTS,
    PREVIOUS_MONTH,
    PREVIOUS_COUNT,
    PREVIOUS_POSTS,
    CURRENT_COUNT - PREVIOUS_COUNT AS ABSOLUTE_CHANGE,
    CASE 
      WHEN PREVIOUS_COUNT = 0 AND CURRENT_COUNT > 0 THEN 999999
      WHEN PREVIOUS_COUNT > 0 THEN 
        ROUND((CURRENT_COUNT - PREVIOUS_COUNT) * 100.0 / PREVIOUS_COUNT, 2)
      ELSE 0
    END AS GROWTH_RATE_PERCENT,
    CASE 
      WHEN PREVIOUS_COUNT = 0 AND CURRENT_COUNT > 0 THEN NULL
      WHEN PREVIOUS_COUNT > 0 THEN 
        ROUND(CURRENT_COUNT * 1.0 / PREVIOUS_COUNT, 2)
      ELSE NULL
    END AS GROWTH_MULTIPLIER,
    CASE WHEN PREVIOUS_COUNT = 0 AND CURRENT_COUNT > 0 THEN TRUE ELSE FALSE END AS IS_NEW_EMERGENCE
  FROM month_comparison
)
SELECT 
  CURRENT_MONTH,
  NGRAM,
  NGRAM_SIZE,
  CURRENT_COUNT,
  CURRENT_POSTS,
  PREVIOUS_MONTH,
  PREVIOUS_COUNT,
  PREVIOUS_POSTS,
  ABSOLUTE_CHANGE,
  GROWTH_RATE_PERCENT,
  GROWTH_MULTIPLIER,
  IS_NEW_EMERGENCE,
  CASE 
    WHEN IS_NEW_EMERGENCE THEN 'NEW'
    WHEN GROWTH_RATE_PERCENT >= 100 THEN 'RAPID_GROWTH'
    WHEN GROWTH_RATE_PERCENT >= 50 THEN 'STRONG_GROWTH'
    WHEN GROWTH_RATE_PERCENT >= 20 THEN 'MODERATE_GROWTH'
    WHEN GROWTH_RATE_PERCENT > 0 THEN 'SLOW_GROWTH'
    WHEN GROWTH_RATE_PERCENT = 0 THEN 'STABLE'
    ELSE 'DECLINING'
  END AS TREND_CATEGORY
FROM trend_metrics
ORDER BY 
  CURRENT_MONTH DESC,
  ABSOLUTE_CHANGE DESC,
  GROWTH_RATE_PERCENT DESC;

